### ISSUE TITLE
Turn-Off-the-Light for local file

### ISSUE THREAD

**Issue by dozortsev** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#1]
How to enable plugin under Google Chrome for local file like `pdf` ?

**Comment by turnoffthelights** [comment]
Hi there,
For this it need the Google "file://" permission in the manifest.json file. 

Thanks,
Stefan

**Comment by dozortsev** [comment]
@turnoffthelights So if I just add `"file://*/*"` pattern to `permission` array in `manifest.json` it should work ?

**Comment by turnoffthelights** [comment]
Yes. (For the security of the browser I did not include this code in the Chrome extension.)

**Comment by dozortsev** [comment]
@turnoffthelights Add pattern to `manifest.json` and restart Google Chrome but it still doesn't work (the icon doesn't appear in URL). 

     "permissions": [ "file:///*/*", "file://*/*", "http://*/*", "https://*/*", "contextMenus", "notifications", "tabs", "storage" ],

**Comment by turnoffthelights** [comment]
Permission must be this:
"permissions": [
    "file://*/*"
]
If error in manifest -> nothing show up
And in the online PDF sample? http://www.analysis.im/uploads/seminar/pdf-sample.pdf

**Comment by dozortsev** [comment]
Still same:

![1]
[1]: http://i.imgur.com/ZQhBQD6.png

**Comment by dozortsev** [comment]
I removed `"http://*/*", "https://*/*"` patterns from `permission` and restart Chrome. Plugin work well, seems Chrome doesn't reload changes from `manifest.json`...

**Comment by turnoffthelights** [comment]
So now you see it only on "file" and not on "http"?

**Comment by dozortsev** [comment]
@turnoffthelights  No. See only in `http` and `https` :(

**Comment by turnoffthelights** [comment]
I will research it here now in my Chrome dev.

**Comment by dozortsev** [comment]
@turnoffthelights So when you add `file://*/*` regex in your `manifest.json` you could use plugin in local files ?

**Comment by turnoffthelights** [comment]
Normal yes. What Chrome version do you use? Do you this github version or the Chrome web store version?

**Comment by dozortsev** [comment]
@turnoffthelights Chrome Version: 40.0.2214.115 and Plugin version is 3.1.0.6. Plugin was installed from web store.

**Comment by turnoffthelights** [comment]
I see in the Turn Off the Lights code that there is an URL check, if you go to js/background.js and comment the line 123 	=>		if ((tab.url.match(/^http/i)) 

And the 'manifest.json' this code   "permissions": [ "http://*/*", "https://*/*", "contextMenus", "notifications", "tabs", "storage", "file:///"]

**Comment by turnoffthelights** [comment]
Maybe a good idea to improve this code with this: https://developer.chrome.com/extensions/activeTab because this works for http, https and file URL.

**Comment by turnoffthelights** [comment]
update: if use  `activatab` it shows the lamp. But other features doesn't work such as the Eye Protection, Night Mode

**Comment by dozortsev** [comment]
@turnoffthelights When I add change in `background.js`. After restarting browser lamp icon disappear and in extensions settings with this plugin I have message: 

> This extension may have been corrupted.

This way also doesn't work. Can you add this feature in the next release ?

**Comment by turnoffthelights** [comment]
Default it will be `http` and `https` for the user safety. But I think I can add an option (Permission option in the 'Advanced Options') see this help page `Step 3: Request optional permissions` https://developer.chrome.com/extensions/permissions

**Comment by dozortsev** [comment]
@turnoffthelights lol. I commented if in `background.js` file and load plugin as [Load Unpacked Extension][1]. Now when I open local `pdf` lamp icon is present but doesn't work. On `http` URLs its work perfect.

[1]: http://superuser.com/a/247654/268507

**Comment by turnoffthelights** [comment]
You use the Chrome PDF viewer? (normal default enabled)
I test it before, and it sure work on `file://` and `http`.

I use the "Load Unpacked", but I did also the test to change it here `C:\Users\Stefan\AppData\Local\Google\Chrome\User Data\Default\Extensions\bfbmjmiodbnnpllbbbfblcplfjjepjdn` but because security of @googlechrome you can't change the `manifest.json` file (-> use cache version)
(update coming very soon)

**Comment by turnoffthelights** [comment]
file permission must be added else you see only the gray lamp icon. And when you click on it -> do nothing

**Comment by turnoffthelights** [comment]
Must be OK now see github Turn Off the Lights Chrome extension v3.1.0.9 and later on the Chrome web store

**Comment by dozortsev** [comment]
@turnoffthelights Yes :+1:. Now it works on local files. When the extension will be present in Chrome store with version 3.1.0.9 ? Because now I has a problem with often opened tag that say me: `You just installed a fake Chrome extension that steals my official Turn Off the Lights source code...`

**Comment by turnoffthelights** [comment]
That is a protection for non-developer that copy the code or republish it (in the Chrome web store). The v3.1.0.9 is rolling now out, it need +/- 60 minutes.

**Comment by dozortsev** [comment]
@turnoffthelights Ok. Thank you for your great commitment. Great extension.
