### ISSUE TITLE
certain elements on youtube on wrong layer

### ISSUE THREAD

**Issue by joshwiker14** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#2]
the problem: youtube's debug tools and other items are hidden behind the video.

Whats expected to happen: Youtube's items to be above the video when they are shown. (e.g. any item in the right-click menu of the video, other video thumbnails after current video is finished)

I only found out what was happening because I did a little digging through chrome's webpage debug tools to change the layers of the UI parts.

chrome version: 41.0.2272.118 (Official Build)
ToTL version: 3.1.0.12
any youtube video
all other etensions disabled

if you need more information, like ToTL settings, feel free to ask.

**Comment by turnoffthelights** [comment]
Hi there,

I can see the YouTube contextmenu ("Get video URL, ...,"Stats for nerds", "About the HTML5 player") when I click right on the YouTube video player.

Can you share me a screenshot of this issue? And do you use the "Flash Detection" feature?

Thanks for using the Turn Off the Lights extension!
Thanks,
Stefan

**Comment by joshwiker14** [comment]
It appears I need to clarify a bit. the context menu is visible to me, but things like "stats for nerds" are obscured once the lights have been turned off.

The following screenshots were taken in Incognito mode, with ToTL the only extension allowed.
Also, I have verified that this problem does not happen without ToTL.

You can see the context menu here.
![2015-04-04-134313_1920x1200_scrot](https://cloud.githubusercontent.com/assets/5994403/6994321/c6d457b0-dad2-11e4-813b-3aa30fe2a22e.png)

Here I have activated the "stats for nerds", but it is only partially visible because it is obscured by the video.
![2015-04-04-134319_1920x1200_scrot](https://cloud.githubusercontent.com/assets/5994403/6994338/4cdc2f9a-dad3-11e4-9118-7d1641447a6a.png)

In these three pictures, I locate the info panel (aka stats for nerds) and change its z-index from 968 to 1000.
![2015-04-04-134342_1920x1200_scrot](https://cloud.githubusercontent.com/assets/5994403/6994352/bd27a4c8-dad3-11e4-874b-dc0781344233.png)
![2015-04-04-134355_1920x1200_scrot](https://cloud.githubusercontent.com/assets/5994403/6994355/c1d6582a-dad3-11e4-9685-5f58df714c31.png)
![2015-04-04-134410_1920x1200_scrot](https://cloud.githubusercontent.com/assets/5994403/6994356/c9a54458-dad3-11e4-952e-4bdf87ef1009.png)

And this I was able to reproduce after the end of the video, with youtube's "autoplay" feature turned off,

**Comment by joshwiker14** [comment]
whoops character limit.

And this I was able to reproduce after the end of the video, with youtube's "autoplay" feature turned off, by toggling the lights on then off. But sometimes it happened without toggling the lights after the video.

and my flash detection setting is set to "Show all Flash objects".

**Comment by turnoffthelights** [comment]
Ah that window. Thanks to report this!
I will add a z-index rule for this debug window.
The update is coming in Turn Off the Lights v3.1.0.14 within few hours and here in github.

Thanks,

**Comment by joshwiker14** [comment]
oh! I almost forgot. The same thing happens with the other options from
that context menu, I was just using the stat window as an example for
simplicity.


-Joshua Wiker

**Comment by turnoffthelights** [comment]
I will check all the  items in the context menu. :)

**Comment by turnoffthelights** [comment]
The code update is now online in github. For Chrome web store it need 60 minutes for public.

**Comment by joshwiker14** [comment]
great to hear!


-Joshua Wiker

**Comment by joshwiker14** [comment]
and thank you for being helpful and quick!


-Joshua Wiker

**Comment by turnoffthelights** [comment]
When you have the latest version... please test it and feedback me :)
Here in my Chrome dev see all the YouTube debug windows, and URL copy field..

**Comment by joshwiker14** [comment]
I will.


-Joshua Wiker

**Comment by joshwiker14** [comment]
It is fixed!
Thank you much!
