### ISSUE TITLE
Works only on youtube

### ISSUE THREAD

**Issue by AakashRaina** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#3]
For other sites featuring videos,the whole page goes black.

**Comment by turnoffthelights** [comment]
Have you tried to enable the "Flash Detection" in the Turn Off the Lights options page?
This feature search for all the flash player, and push this on top of the black layer. (default disabled for new users, this information can you read also in the "Welcome Guide" when you install Turn Off the Lights for the first time).

Thanks
