### ISSUE TITLE
causes videos to not start playing or to stop playing

### ISSUE THREAD

**Issue by ctrl-f5** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#4]
I've searched months why youtube was being all flaky, drove me nuts. Finally found out it was this extension. chrome 46 (and previous versions) on OSX 10.10.

- when loading youtube, the video doesn't play. When clicking it is paused, need to lick it again to make it actually play.
- when playing a playlist, 1 need to click every new video that starts 2 times to make it actually play...
- when it is playing and I hover over the preview of another video in the sidebar, the video stops playing.
- when it is playing and I scroll down, the video stops playing.

All this happens with just the extension activated in the extension manager, it's not even in use.

**Comment by turnoffthelights** [comment]
Please for questions or bug report use the support form: www.turnoffthelights.com/support/

**Comment by turnoffthelights** [comment]
Do you use any other Chrome extensions? Have you tried to disable this one by one except Turn Off the Lights?
What feature have you enabled in the Turn Off the Lights extension?
Have you tried to reinstall the Turn Off the Lights Chrome extension?

Thanks,

**Comment by turnoffthelights** [comment]
Possible you are using the 'AutoStop' feature. Disable this option in the "Turn Off the Lights" options page so it play the video automatically.

note:
Turn Off the Lights v3.2 Chrome extension is now online! This update contains bug fixes and improvements including the 'AutoStop' feature.
