### ISSUE TITLE
Night Mode switch is visible in full-screen mode

### ISSUE THREAD

**Issue by avi12** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#7]
Extension version: 4.1.5.0
Running Microsoft Edge 83.0.478.37

I enabled the Night Mode switch
The problem is that it's always visible - even in full-screen mode, e.g. while watching YouTube, which blocks off a small portion and just distracts

**Comment by turnoffthelights** [comment]
Hi @avi12 

Thank you to report this!
You can always hide the switch, and use this option in the Night Mode tab "Make the page go dark or light by long-pressing the current web page"

Please for questions or need help use next the time the support form at https://www.turnoffthelights.com/support/

Thanks,

**Comment by avi12** [comment]
Thank you
I am aware of this option
However, I do like having the switch, yet placing in full-screen isn't ideal

**Comment by turnoffthelights** [comment]
Fixed in release v4.1.7.0.
When the video is playing it will hide the Night Mode switch.
