### ISSUE TITLE
Intall fails in Windows XP

### ISSUE THREAD

**Issue by Getfree** [turnoffthelights/Turn-Off-the-Lights-Chrome-extension#8]
Installation fails with the following error in Windows XP (Chrome version 49).
Screenshot: https://i.snipboard.io/Kfta0H.jpg

I have tried on several computers, it's the same problem everywhere an older Chrome version is used.

I can install any other extension from the web store just fine under Windows XP. It's just this one extension that fails to install.

Here is direct link to a BrowserLing session using Chrome 49.
Just click on the "Add to Chrome" blue button and you'll see the error.
https://www.browserling.com/browse/win/7/chrome/49/https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fbfbmjmiodbnnpllbbbfblcplfjjepjdn

**Comment by turnoffthelights** [comment]
Hi there,

That is an issue on the Chrome web store side and not an issue on the Turn Off the Lights Chrome extension. Please contact the Google Chrome help forum:
https://support.google.com/chrome/community?hl=en

The steps you can try to solve that issue:
1. Restart your computer
2. Change where Chrome downloads files to your desktop folder
3. Edit your hosts file and remove the line "127.0.0.1"

If all else fails, install Turn Off the Lights manually by download the CRX file from another computer. And move the downloaded CRX file in the Chrome://extension page.

Please for questions or need help use next time the support contact form at https://www.turnoffthelights.com/support

Thanks

**Comment by Getfree** [comment]
There's no contact form or any way to contact anybody in that website.
The closest thing to a contact method is a "Follow us" link to twitter or facebook.

And it's not an issue on the Chrome Web Store. I can install any other extension from the store using Windows XP and Vista.
It's just this specific extension that fails to install.

**Comment by turnoffthelights** [comment]
Hi there,

We upload the zip file to the Chrome web store, and we can then change nothing in this package. The Chrome web store manage completely this website. And in the manifest version we set the support to "minimum_chrome_version": "33".

https://www.turnoffthelights.com/support/
At the bottom of the web page, you see a blue button for "Email Support" and "Live Chat".

Thanks
